//Job types
export const JOB_SEARCH_START = 'JOB_SEARCH_START'
export const JOB_SEARCH_SUCCESS = 'JOB_SEARCH_SUCCESS'
export const JOB_SEARCH_FAILURE = 'JOB_SEARCH_FAILURE'

export const FETCH_JOB_DETAIL_START = 'FETCH_JOB_DETAIL_START'
export const FETCH_JOB_DETAIL_SUCCESS = 'FETCH_JOB_DETAIL_SUCCESS'
export const FETCH_JOB_DETAIL_FAILURE = 'FETCH_JOB_DETAIL_FAILURE'

export const APPLY_JOB_START='APPLY_JOB_START'
export const APPLY_JOB_SUCCESS='APPLY_JOB_SUCCESS'
export const APPLY_JOB_FAILURE='APPLY_JOB_FAILURE'

export const FETCH_JOB_APPLICANTS_START='FETCH_JOB_APPLICANTS_START'
export const FETCH_JOB_APPLICANTS_SUCCESS='FETCH_JOB_APPLICANTS_SUCCESS'
export const FETCH_JOB_APPLICANTS_FAILURE='FETCH_JOB_APPLICANTS_FAILURE'

//Post Types
export const CREATE_NEW_POST_START='CREATE_NEW_POST_START'
export const CREATE_NEW_POST_SUCCESS='CREATE_NEW_POST_SUCCESS'
export const CREATE_NEW_POST_FAILURE='CREATE_NEW_POST_FAILURE'

export const FETCH_LATEST_POSTS_START='FETCH_LATEST_POSTS_START'
export const FETCH_LATEST_POSTS_SUCCESS='FETCH_LATEST_POSTS_SUCCESS'
export const FETCH_LATEST_POSTS_FAILURE='FETCH_LATEST_POSTS_FAILURE'
export const LIKE_POST='LIKE_POST'
export const UNLIKE_POST='UNLIKE_POST'