export const JOB_SEARCH_START = 'JOB_SEARCH_START'
export const JOB_SEARCH_SUCCESS = 'JOB_SEARCH_SUCCESS'
export const JOB_SEARCH_FAILURE = 'JOB_SEARCH_FAILURE'

export const FETCH_JOB_DETAIL_START = 'FETCH_JOB_DETAIL_START'
export const FETCH_JOB_DETAIL_SUCCESS = 'FETCH_JOB_DETAIL_SUCCESS'
export const FETCH_JOB_DETAIL_FAILURE = 'FETCH_JOB_DETAIL_FAILURE'

export const APPLY_JOB_START='APPLY_JOB_START'
export const APPLY_JOB_SUCCESS='APPLY_JOB_SUCCESS'
export const APPLY_JOB_FAILURE='APPLY_JOB_FAILURE'